getwd()
setwd("/home/santosh/Desktop/DATA_SCIENCE/tenth_week")
install.packages("randomForest")
library("randomForest")
telecom_data = read.csv("Telecom_Data.csv", na.strings = "")
telecom_data = telecom_data[-4]
telecom_data$churn = as.factor(telecom_data$churn)
library("caTools")
sample = sample.split(telecom_data$churn, SplitRatio = 0.80)
train_data = subset(telecom_data, sample == TRUE)
test_data = subset(telecom_data, sample == FALSE)
model = randomForest(churn~., data = train_data)
test_data$predicted_churn = predict(model,test_data)
table(test_data$churn, test_data$predicted_churn)
